name: Continuous Integration

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

      - name: lua tests
        run: devenv shell task test-lua

      - name: pdf end-to-end test
        run: devenv shell task test-pdf

      - name: document
        run: devenv shell l3build-wrapped doc

      - name: build
        run: devenv shell l3build-wrapped ctan -q -H --show-log-on-error

  versionary:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: versionary
        uses: jolars/versionary@v0
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
