name: Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          packages: >
            l3build scheme-basic fontawesome5 pdfcol tikzfill float caption
            hypdoc koma-script xcolor lualatex-math unicode-math fancyvrb
            booktabs mdwtools parskip tcolorbox luatexbase

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - uses: leafo/gh-actions-lua@v13

      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 8

      - name: Install texweave
        run: pnpm add -g texweave

      - name: Extract DTX documentation
        run: texweave extract

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_site

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
